FROM node:16-alpine
WORKDIR /app

# Copy package files from root, where package.json actually is
COPY package*.json /app/
RUN npm install --only=production

# Copy only backend code from Backend folder
COPY Backend/. /app/

EXPOSE 5000
CMD ["node", "index.js"]
